-- 公開美食團搜尋 + 收藏(星星數)

begin;

-- 1) groups: public flag + favorite count
alter table if exists public.groups
  add column if not exists is_public boolean not null default false;

alter table if exists public.groups
  add column if not exists favorite_count integer not null default 0;

create index if not exists groups_is_public_idx on public.groups (is_public);
create index if not exists groups_favorite_count_idx on public.groups (favorite_count desc);

-- 2) favorites table
create table if not exists public.group_favorites (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (group_id, user_id)
);

alter table public.group_favorites enable row level security;

-- 3) RLS policies for group_favorites (own rows only)
drop policy if exists group_favorites_select_own on public.group_favorites;
drop policy if exists group_favorites_insert_own on public.group_favorites;
drop policy if exists group_favorites_delete_own on public.group_favorites;

create policy group_favorites_select_own
  on public.group_favorites
  for select
  using (user_id = auth.uid());

create policy group_favorites_insert_own
  on public.group_favorites
  for insert
  with check (user_id = auth.uid());

create policy group_favorites_delete_own
  on public.group_favorites
  for delete
  using (user_id = auth.uid());

-- 4) helper: is_group_public
create or replace function public.is_group_public(p_group_id uuid)
returns boolean
language sql
security definer
set search_path = public
set row_security = off
as $$
  select coalesce((select g.is_public from public.groups g where g.id = p_group_id), false);
$$;

-- 5) update existing RLS policies to allow selecting public groups/foods

-- groups select: member OR public
-- NOTE: policy name in existing file is "groups_select_member"; we replace it here.
drop policy if exists "groups_select_member" on public.groups;
drop policy if exists "groups_select_public_or_member" on public.groups;

create policy "groups_select_public_or_member"
  on public.groups
  for select
  using (public.is_group_member(id) or is_public = true);

-- foods select: member OR group is public
-- NOTE: existing policy name is "foods_select_same_group"; we replace it here.
drop policy if exists "foods_select_same_group" on public.foods;
drop policy if exists "foods_select_public_or_member" on public.foods;

create policy "foods_select_public_or_member"
  on public.foods
  for select
  using (public.is_group_member(group_id) or public.is_group_public(group_id));

-- ratings select: keep as-is (still limited to group members)

-- 6) favorite_count maintenance triggers
create or replace function public.recount_group_favorite_count(p_group_id uuid)
returns void
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  update public.groups g
  set favorite_count = (
    select count(*)::int
    from public.group_favorites gf
    where gf.group_id = p_group_id
  )
  where g.id = p_group_id;
end;
$$;

create or replace function public.tg_group_favorites_recount()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  v_group_id uuid;
begin
  v_group_id := coalesce(new.group_id, old.group_id);
  perform public.recount_group_favorite_count(v_group_id);
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_group_favorites_recount_ins on public.group_favorites;
drop trigger if exists trg_group_favorites_recount_del on public.group_favorites;

create trigger trg_group_favorites_recount_ins
after insert on public.group_favorites
for each row execute function public.tg_group_favorites_recount();

create trigger trg_group_favorites_recount_del
after delete on public.group_favorites
for each row execute function public.tg_group_favorites_recount();

-- 7) RPC: search public groups by keyword (group name or food name)
create or replace function public.search_public_groups(p_keyword text default '', p_limit int default 50)
returns table (
  id uuid,
  name text,
  description text,
  owner_id uuid,
  is_public boolean,
  favorite_count int,
  matched_food_count int,
  is_favorited boolean
)
language sql
security definer
set search_path = public
set row_security = off
as $$
  with kw as (
    select nullif(trim(coalesce(p_keyword, '')), '') as q
  )
  select
    g.id,
    g.name,
    g.description,
    g.owner_id,
    g.is_public,
    g.favorite_count,
    count(distinct f.id)::int as matched_food_count,
    exists(
      select 1
      from public.group_favorites gf
      where gf.group_id = g.id
        and gf.user_id = auth.uid()
    ) as is_favorited
  from public.groups g
  left join public.foods f
    on f.group_id = g.id
   and (
      (select q from kw) is not null
      and f.name ilike ('%' || (select q from kw) || '%')
   )
  where g.is_public = true
    and (
      (select q from kw) is null
      or g.name ilike ('%' || (select q from kw) || '%')
      or exists (
        select 1
        from public.foods f2
        where f2.group_id = g.id
          and f2.name ilike ('%' || (select q from kw) || '%')
      )
    )
  group by g.id
  order by g.favorite_count desc, g.name asc
  limit greatest(1, least(coalesce(p_limit, 50), 200));
$$;

-- Allow authenticated users to call RPC
revoke all on function public.search_public_groups(text, int) from public;
grant execute on function public.search_public_groups(text, int) to authenticated;

commit;
